#! /bin/bash

if [ $# -ne 1 -a $# -ne 3 ]
  then
    echo "usage: ./deploy SCRIPT[ as NAME]"
    exit
fi

TARGET=$(readlink -en $1)

if [ $# -eq 3 ]
  then
    sudo ln -s $TARGET /usr/local/bin/$3
    exit
fi

sudo ln -s $TARGET /usr/local/bin/$1
