#! /bin/bash

if [ $# -ne 1 -a $# -ne 3 ]
  then
    echo "usage: ./deploy SCRIPT[ as NAME]"
    exit
fi

if [ $# -eq 3 ]
  then
    sudo cp $1 /usr/local/bin/$3
    exit
fi

sudo cp $1 /usr/local/bin/$1
